config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'events#index'
  resources :events do
    resources :comments
  end
  resources :participants, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resources :users, only: %i[show]
  resources :relationships, only: %i[create destroy]
  get 'tags/:tag', to: 'events#index', as: :tag

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 16 }

  # Include default devise modules. Others available are:
  # :confirmable :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  has_many :events, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_events, through: :favorites, source: :event
  has_many :participant_events, through: :participants, source: :event
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # ランダムな文字列を作成
  def self.create_unique_string
    SecureRandom.uuid
  end

  # facebookで認証できるユーザを見つける
  def self.find_for_facebook(auth)
    user = User.find_by(email: auth.info.email)

    user ||= User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid: auth.uid,
                      password: Devise.friendly_token[0, 20])
    user.save
    user
  end

  # ransackで有効な属性を指定
  def self.ransackable_attributes(_auth_object = nil)
    %w[name]
  end

  # ransackで有効なアソシエーションを指定
  def self.ransackable_associations(_auth_object = nil)
    []
  end

  # フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def build_resource(hash = {})
    hash[:uid] = User.create_unique_string
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_event_tab.html.erb
<div class="card horizontal">
  <div class="card-stacked">
    <div class="card-content">
      <%= content_tag(:div, "開催済み", class: "card-finished") if event.event_at < Date.current %>
      <%= event.image.attached? ? image_tag(event.image_resize(280)) : image_tag('noimage.png') %>
      <%= link_to event.title, event_path(event), class: "event-title" %><br />
      <div class="card-content-memo">
        <i class="material-icons tiny">location_on</i><%= event.location %><br />
        <i class="material-icons tiny">access_time</i><%= l event.event_at if event.event_at.present? %>
      </div>
    </div>
    <% if user_signed_in? && event.user_id == current_user.id %>
    <div class="card-action">
      <%= link_to '開催を中止する', event, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/_follow_link.html.erb
<% if current_user.active_relationships.find_by(followed_id: user.id) %>
  <%= link_to 'フォローしない', relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), method: :delete, remote: true, class: "btn waves-effect waves-light"%>
<% else %>
  <%= link_to 'フォローする', relationships_path(followed_id: user.id), method: :post, remote: true, class: "btn waves-effect waves-light" %>
<% end %>

app/views/users/_follow_tag.html.erb
<span id="follow_tag_<%= user.id %>">
<%= "フォロー中のユーザです！" if user_signed_in? && current_user.following?(user) %>
</span>

app/views/users/_follower_tab.html.erb
<% user.followers.each do |u| %>
  <%= link_to u.name, user_path(u) %><br />
<% end %>

app/views/users/show.html.erb
<% if @user.try(:admin?) %>
  <h3>【管理者】<%= @user.name %>のページ</h3>
<% else %>
  <h3><%= @user.name %>のページ</h3>
<% end %>
<%= render 'follow_tag', user: @user %>

<%= link_to_if(user_signed_in? && current_user == @user, 'プロフィールの編集はこちら', edit_user_registration_path ){} %>

<% unless current_user.blank? || current_user == @user %>
<div id="follow_link_<%= @user.id %>">
<%= render 'follow_link', user: @user %>
</div>
<% end %>

<br />

<h4>勉強会管理</h4>
<div class="row event_tab">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s4"><a href="#event_tab1">参加</a></li>
      <li class="tab col s4"><a href="#event_tab2">開催</a></li>
      <li class="tab col s4"><a href="#event_tab3">お気に入り</a></li>
    </ul>
  </div>
  <div id="event_tab1" class="col s12">
    <% @user.participant_events.each do |event| %>
      <%= render 'event_tab', event: event %>
    <% end %>
  </div>
  <div id="event_tab2" class="col s12">
    <% @user.events.includes(:image_attachment).each do |event| %>
      <%= render 'event_tab', event: event %>
    <% end %>
  </div>
  <div id="event_tab3" class="col s12">
    <% @user.favorite_events.each do |event| %>
      <%= render 'event_tab', event: event %>
    <% end %>
  </div>
</div>

<h4>フォロー管理</h4>
<div class="row event_tab">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s6"><a href="#event_tab4">フォロー</a></li>
      <li class="tab col s6"><a href="#event_tab5">フォロワー</a></li>
    </ul>
  </div>
  <div id="event_tab4" class="col s12">
    <% @user.following.each do |user| %>
      <%= link_to user.name, user_path(user) %><br />
    <% end %>
  </div>

  <div id="event_tab5" class="col s12">
    <%= render 'follower_tab', user: @user %>
  </div>
</div>