config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'events#index'
  resources :events do
    resources :comments
  end
  resources :participants, only: %i[create destroy]
  resources :favorites, only: %i[create destroy]
  resources :users, only: %i[show]
  resources :relationships, only: %i[create destroy]
  get 'tags/:tag', to: 'events#index', as: :tag

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/event.rb
class Event < ApplicationRecord
  include CommonModule
  belongs_to :user
  has_many :participants, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image
  has_many :favorite_users, through: :favorites, source: :user
  has_many :participant_users, through: :participants, source: :user
  acts_as_taggable

  paginates_per 12

  validates :title, presence: true, length: { maximum: 32 }
  validates :location, presence: true, length: { maximum: 32 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :event_at, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :expiration_date_cannot_be_in_the_past

  # 過去の開催日は許容しないバリデーション
  def expiration_date_cannot_be_in_the_past
    errors.add(:event_at, 'は過去の日付は使えません') if event_at.present? && event_at < Date.today
  end

  # ransackで有効な属性を指定
  def self.ransackable_attributes(_auth_object = nil)
    %w[title content created_at event_at]
  end

  # ransackで有効なアソシエーションを指定
  def self.ransackable_associations(_auth_object = nil)
    %w[user]
  end

  # 画像のリサイズ
  def image_resize(size)
    image.variant(resize: "#{size}x#{size}").processed
  end

  # イベントが開催済みか
  def held?
    event_at < Date.current
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit create update destroy]

  def index
    # @events = Event.all
    @search = if params[:tag]
                Event.tagged_with(params[:tag]).ransack(params[:q])
              else
                Event.ransack(params[:q])
              end
    @events = @search.result(distinct: true).order_desc.page(params[:page])
    @events = @events.includes(image_attachment: :blob)
  end

  def show
    # @participant = current_user.participants.find_by(event_id: @event.id) if user_signed_in?
    # @favorite = current_user.favorites.find_by(event_id: @event.id) if user_signed_in?
    @comments = @event.comments.includes(:user).order_desc

    @comment = @event.comments.build
  end

  def new
    @event = Event.new
  end

  def edit
    redirect_to @event, notice: 'アクセス権がありません' unless @event.user_id == current_user.id
  end

  def create
    @event = current_user.events.build(event_params)
    @event.tag_list.add(params[:event][:tag_list])

    if @event.save
      redirect_to @event, notice: 'イベントが作成されました！'
    else
      render :new
    end
  end

  def update
    if @event.user_id == current_user.id
      @event.tag_list.clear
      @event.tag_list.add(params[:event][:tag_list])

      @event.update(event_params) ? redirect_to(@event, notice: 'イベントが更新されました！') : render('edit')
    else
      redirect_to @event, notice: '権限がありません'
    end
  end

  def destroy
    if @event.user_id == current_user.id
      @event.destroy
      redirect_to events_url, notice: 'イベントが削除されました！'
    else
      redirect_to @event, notice: '権限がありません'
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :content, :event_at, :image, :tag_list, :location, :price, :capacity)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_favorite_link.html.erb
<div id="favorite_link_<%= "#{event.id}" %>">
<% if current_user.favorites.find_by(event_id: event.id) %>
<%= link_to 'あとで見るを取り消す',
            favorite_path(current_user.favorites.find_by(event_id: event.id)),
            method: :delete,
            remote: true,
            onclick: "M.toast({html: '「#{event.title}」をお気に入りから解除しました', displayLength: 2000})",
            class: 'btn waves-effect waves-light' %>
<% else %>
<%= link_to 'あとで見る',
            favorites_path(event_id: event.id),
            method: :post,
            remote: true,
            onclick: "M.toast({html: '「#{event.title}」をお気に入りに登録しました', displayLength: 2000})",
            class: 'btn waves-effect waves-light' %>
<% end %>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, placeholder: '具体的な説明を書きましょう！' %>
  </div>

  <div class="field">
    <%= form.label :location %><br />
    <%= form.text_field :location %>
  </div>

  <div class="field row">
    <div class="col s3">
    <%= form.label :price %><br />
    <%= form.number_field :price, placeholder: '数値のみ入力可／単位は円', min: 0 %>
    </div>

    <div class="col s3 push-s1">
    <%= form.label :event_at %><br />
    <%= form.date_field :event_at, class: 'datepicker' %>
    </div>

    <div class="col s3 push-s2">
    <%= form.label :capacity %><br />
    <%= form.number_field :capacity, placeholder: '数値のみ入力可／単位は人', min: 0 %>
    </div>
  </div>

  <div class="field">
    <%= form.label :tag_list, "タグ一覧" %><br />
    <% Event.tag_counts.each do |tag| %>
      <label>
        <%= form.check_box :tag_list, { multiple: true , include_hidden: false}, tag[:name] %>
        <span><%= tag.name %></span>
      </label>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :image %><br />
    <%= form.file_field :image %>
  </div>

  <br />

  <div class="actions">
    <%= form.submit  class: 'btn waves-effect waves-light' %>
  </div>
<% end %>

app/views/events/_participants.html.erb
<div id="participants_<%= "#{@event.id}" %>">
  <p>
    <strong>参加人数:</strong>
    <%= "#{@event.participants.count}名" %>
  </p>
  <p>
    <strong>参加者:</strong>
    <% @event.participant_users.each do |user| %>
      <br>・<%= user.name %>
    <% end %>
  </p>
</div>

app/views/events/_participate_link.html.erb
<div id="participate_link_<%= "#{event.id}" %>">
<% if current_user.participants.find_by(event_id: event.id) %>
<%= link_to 'キャンセルする',
            participant_path(current_user.participants.find_by(event_id: event.id)),
            method: :delete,
            remote: true,
            onclick: "M.toast({html: '「#{event.title}」の参加登録をキャンセルしました', displayLength: 2000})",
            class: 'btn waves-effect waves-light' %>
<% elsif event.capacity <=  event.participants.count %>
<%= '定員に達しているため参加できません' %>
<% else %>
<%= link_to '参加する',
            participants_path(event_id: event.id),
            method: :post,
            remote: true,
            onclick: "M.toast({html: '「#{event.title}」を参加登録しました', displayLength: 2000})",
            class: 'btn waves-effect waves-light' %>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %>|
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<br>
<div class="row">
  <%= search_form_for @search do |f| %>
  <%= f.search_field :title_cont, placeholder: "勉強会を検索する", class: "col s8"  %>
  <%= f.submit "検索", class: "btn waves-effect waves-light search col s1", data: { disable_with: "送信中..." }  %>
  <%= link_to 'クリア', request.path, class: "btn waves-effect waves-light left col s1", data: { disable_with: "送信中..." } %>
  <% end %>
</div>

<br />

<div class="right">
<%= sort_link(@search, :created_at, "投稿日で並び替える", hide_indicator: false) %>／
<%= sort_link(@search, :event_at, "開催日で並び替える", hide_indicator: false) %>
</div>

<br />

<div class="row flex">
<% @events.each do |event| %>
  <div class="col s12 m6 l4">
    <div class="card">
      <div class="card-image">
        <%= content_tag(:div, "開催済み", class: "card-finished") if event.held? %>
        <%= event.image.attached? ? image_tag(event.image_resize(200)) : image_tag('noimage.png') %>
      </div>
      <div class="card-content">
        <%= link_to event.title, event, class: "event-title" %>
        <%= render 'favorite_link', event: event if user_signed_in? %>
      </div>
    </div>
  </div>
<% end %>
</div>

<%= paginate @events %>
<%= page_entries_info @events %>

app/views/events/new.html.erb
<h3>勉強会を投稿する</h3>
<%= render 'form', event: @event %>
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <%= @event.image.attached? ? image_tag(@event.image_resize(200)) : image_tag('noimage.png')  %>
</p>

<p>
  <strong>タイトル:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>詳細:</strong>
  <%= @event.content %>
</p>

<p>
  <strong>開催地:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>料金:</strong>
  <%= "#{@event.price}円" %>
</p>

<p>
  <strong>開催日:</strong>
  <%= l @event.event_at if @event.event_at.present? %>
</p>

<p>
  <strong>開催者:</strong>
  <%= link_to @event.user.name , user_path(@event.user) %>
</p>

<p>
  <strong>定員:</strong>
  <%= "#{@event.capacity}名" %>
</p>

<%= render 'participants', event: @event %>

<p>タグ: <%= @event.tag_list.any? ? raw(@event.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) : 'タグなし' %></p>

<% if user_signed_in? && current_user != @event.user %>
<%= render 'participate_link', event: @event unless @event.held? %>
<br>
<%= render 'favorite_link', event: @event %>
<% end %>


<h3>コメント</h3>
<%= render partial: 'comments/form', locals: { comment: @comment, event: @event } if user_signed_in? %>


<div id="comments_area">
<%= render partial: 'comments/index', locals: { comments: @comments, event: @event } %>
</div>

<%= link_to 'Edit |', edit_event_path(@event) if user_signed_in? && @event.user_id == current_user.id %>
<%= link_to 'Back', events_path %>